/*************************************************************************
 *                                                                       *
 *  EJBCA: The OpenSource Certificate Authority                          *
 *                                                                       *
 *  This software is free software; you can redistribute it and/or       *
 *  modify it under the terms of the GNU Lesser General Public           *
 *  License as published by the Free Software Foundation; either         *
 *  version 2.1 of the License, or any later version.                    *
 *                                                                       *
 *  See terms of license at gnu.org.                                     *
 *                                                                       *
 *************************************************************************/

package org.ejbca.core.ejb.hardtoken;

import java.util.Arrays;
import java.util.Collection;

import junit.framework.TestCase;

import org.apache.log4j.Logger;
import org.ejbca.core.model.SecConst;
import org.ejbca.core.model.hardtoken.HardTokenProfileExistsException;
import org.ejbca.core.model.hardtoken.profiles.EnhancedEIDProfile;
import org.ejbca.core.model.hardtoken.profiles.HardTokenProfile;
import org.ejbca.core.model.hardtoken.profiles.SwedishEIDProfile;
import org.ejbca.core.model.hardtoken.profiles.TurkishEIDProfile;
import org.ejbca.core.model.log.Admin;
import org.ejbca.util.CryptoProviderTools;
import org.ejbca.util.InterfaceCache;

/**
 * Tests the hard token profile entity bean.
 * 
 * @version $Id: HardTokenProfileTest.java 12566 2011-09-14 07:35:29Z anatom $
 */
public class HardTokenProfileTest extends TestCase {
    private static Logger log = Logger.getLogger(HardTokenProfileTest.class);

    private HardTokenSessionRemote hardTokenSession = InterfaceCache.getHardTokenSession();

    private static int SVGFILESIZE = 512 * 1024; // 1/2 Mega char

    private static final Admin admin = new Admin(Admin.TYPE_CACOMMANDLINE_USER);

    public HardTokenProfileTest(String name) {
        super(name);
    }

    public void setUp() throws Exception {
        CryptoProviderTools.installBCProvider();
    }

    public void tearDown() throws Exception {
    }

    /**
     * adds a profile to the database
     * @throws HardTokenProfileExistsException 
     * 
     * @throws Exception
     *             error
     */
    public void test01AddHardTokenProfile() throws HardTokenProfileExistsException {

        final SwedishEIDProfile swedishProfileOrg = new SwedishEIDProfile();
        final EnhancedEIDProfile enhancedProfileOrg = new EnhancedEIDProfile();
        final TurkishEIDProfile turkishProfileOrg = new TurkishEIDProfile();

        final String svgdata = createSVGData();
        swedishProfileOrg.setPINEnvelopeData(svgdata);
        enhancedProfileOrg.setIsKeyRecoverable(EnhancedEIDProfile.CERTUSAGE_ENC, true);
        // It should be possible to indicate that a certificate should not be generated by not specifying a cert profile for this key. 
        swedishProfileOrg.setCertificateProfileId(SwedishEIDProfile.CERTUSAGE_SIGN, SecConst.CERTPROFILE_NO_PROFILE);

        this.hardTokenSession.addHardTokenProfile(admin, "SWETEST", swedishProfileOrg);
        this.hardTokenSession.addHardTokenProfile(admin, "ENHTEST", enhancedProfileOrg);
        this.hardTokenSession.addHardTokenProfile(admin, "TURTEST", turkishProfileOrg);

        final Collection<Integer> authorizedHardTokenIds = this.hardTokenSession.getAuthorizedHardTokenProfileIds(admin);

        final SwedishEIDProfile swedishProfile = (SwedishEIDProfile) this.hardTokenSession.getHardTokenProfile(admin, "SWETEST");
        final EnhancedEIDProfile enhancedProfile = (EnhancedEIDProfile) this.hardTokenSession.getHardTokenProfile(admin, "ENHTEST");
        final TurkishEIDProfile turkishProfile = (TurkishEIDProfile) this.hardTokenSession.getHardTokenProfile(admin, "TURTEST");

        final String svgdata2 = swedishProfile.getPINEnvelopeData();

        assertTrue(  "Profile not authorized", authorizedHardTokenIds.contains( new Integer(this.hardTokenSession.getHardTokenProfileId(admin, "SWETEST")) )  );
        assertTrue("Saving certificate profile failed", swedishProfile.getCertificateProfileId(SwedishEIDProfile.CERTUSAGE_SIGN)==SecConst.CERTPROFILE_NO_PROFILE);
        assertTrue("Saving SVG Data failed", svgdata.equals(svgdata2));
        assertTrue("Saving Hard Token Profile failed", enhancedProfile.getIsKeyRecoverable(EnhancedEIDProfile.CERTUSAGE_ENC));
        assertTrue("Saving Turkish Hard Token Profile failed", turkishProfile!=null);
    }

    /**
     * renames profile
     * 
     * @throws Exception
     *             error
     */
    public void test02RenameHardTokenProfile() throws Exception {
        log.trace(">test02RenameHardTokenProfile()");

        boolean ret = false;
        try {
            hardTokenSession.renameHardTokenProfile(admin, "SWETEST", "SWETEST2");
            ret = true;
        } catch (HardTokenProfileExistsException pee) {
            log.debug("", pee);
        }
        assertTrue("Renaming Hard Token Profile failed", ret);

        log.trace("<test02RenameHardTokenProfile()");
    }

    /**
     * clones profile
     * 
     * @throws Exception
     *             error
     */
    public void test03CloneHardTokenProfile() throws Exception {
        log.trace(">test03CloneHardTokenProfile()");

        boolean ret = false;
        try {
            hardTokenSession.cloneHardTokenProfile(admin, "SWETEST2", "SWETEST");
            ret = true;
        } catch (HardTokenProfileExistsException pee) {
            log.debug("", pee);
        }
        assertTrue("Cloning Hard Token Profile failed", ret);

        log.trace("<test03CloneHardTokenProfile()");
    }

    /**
     * edits profile
     * 
     * @throws Exception
     *             error
     */
    public void test04EditHardTokenProfile() throws Exception {
        log.trace(">test04EditHardTokenProfile()");
        boolean ret = false;
        HardTokenProfile profile = hardTokenSession.getHardTokenProfile(admin, "ENHTEST");
        profile.setHardTokenSNPrefix("11111");
        hardTokenSession.changeHardTokenProfile(admin, "ENHTEST", profile);
        ret = true;
        assertTrue("Editing HardTokenProfile failed", ret);
        log.trace("<test04EditHardTokenProfile()");
    }

    /**
     * removes all profiles
     * 
     * @throws Exception
     *             error
     */
    public void test05removeHardTokenProfiles() throws Exception {
        log.trace(">test05removeHardTokenProfiles()");
        boolean ret = false;
        try {
            // Remove all except ENHTEST
            hardTokenSession.removeHardTokenProfile(admin, "SWETEST");
            hardTokenSession.removeHardTokenProfile(admin, "SWETEST2");
            hardTokenSession.removeHardTokenProfile(admin, "ENHTEST");
            hardTokenSession.removeHardTokenProfile(admin, "TURTEST");
            ret = true;
        } catch (Exception pee) {
            log.debug("", pee);
        }
        assertTrue("Removing Hard Token Profile failed", ret);
        log.trace("<test05removeHardTokenProfiles()");
    }

    private String createSVGData() {
        char[] chararray = new char[SVGFILESIZE];
        Arrays.fill(chararray, 'a');

        return new String(chararray);
    }

}
